"""
training/train.py
──────────────────
QLoRA fine-tuning script — trains a small language model on the
retail + MIMIC training dataset generated by data_prep/dataset_builder.py.

Architecture:
  Base model: microsoft/Phi-3.5-mini-instruct (3.8B params, CPU-friendly)
              OR qwen2.5-coder:7b if GPU is available
  Method: QLoRA (4-bit NF4 quantization + LoRA adapters)
  Trainable: ~0.4% of parameters (q/k/v/o projection matrices)
  Framework: HuggingFace Transformers + PEFT + TRL SFTTrainer

Hardware requirements:
  GPU: ≥6GB VRAM (CUDA)  → full training, ~2 hours for 3 epochs
  CPU: any               → demo run on 50 examples, ~30 min per epoch

Usage
─────
    # Quick demo (CPU, 50 examples, 1 epoch)
    python training/train.py --demo

    # Full training (GPU required)
    python training/train.py --model microsoft/Phi-3.5-mini-instruct --epochs 3

    # With smaller model for CPU
    python training/train.py --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 --epochs 3

Output
──────
    lora_adapters/   ← saved LoRA adapter weights (merge into base for deployment)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DATA_DIR = ROOT / "data"
ADAPTER_DIR = ROOT / "lora_adapters"
TRAIN_DATA = DATA_DIR / "training_dataset.jsonl"
VAL_DATA = DATA_DIR / "validation_dataset.jsonl"


def check_dependencies() -> bool:
    """Check if training dependencies are available."""
    missing = []
    for pkg in ["torch", "transformers", "peft", "trl", "bitsandbytes", "datasets"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        print(f"Missing training dependencies: {missing}")
        print("Install with: pip install torch transformers peft trl bitsandbytes datasets")
        return False
    return True


def load_jsonl(path: Path, max_examples: int | None = None) -> list[dict]:
    """Load JSONL training data."""
    if not path.exists():
        raise FileNotFoundError(
            f"Training data not found: {path}\n"
            "Run: python data_prep/dataset_builder.py"
        )
    examples = []
    with open(path) as f:
        for line in f:
            examples.append(json.loads(line.strip()))
            if max_examples and len(examples) >= max_examples:
                break
    return examples


def format_for_training(example: dict, tokenizer) -> str:
    """Apply the model's chat template to a ChatML example."""
    messages = example["messages"]
    try:
        return tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
    except Exception:
        # Fallback: manual formatting
        text = ""
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            if role == "system":
                text += f"<|system|>\n{content}<|end|>\n"
            elif role == "user":
                text += f"<|user|>\n{content}<|end|>\n"
            elif role == "assistant":
                text += f"<|assistant|>\n{content}<|end|>\n"
        return text


def train(
    model_id: str = "microsoft/Phi-3.5-mini-instruct",
    epochs: int = 3,
    batch_size: int = 1,
    max_seq_length: int = 1024,
    lora_rank: int = 16,
    learning_rate: float = 2e-4,
    demo_mode: bool = False,
    output_dir: str = str(ADAPTER_DIR),
) -> None:
    """Run QLoRA fine-tuning."""
    if not check_dependencies():
        return

    import torch
    from datasets import Dataset
    from peft import LoraConfig, TaskType
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
    )
    from trl import SFTTrainer, SFTConfig

    # ── Hardware detection ─────────────────────────────────────────────────────
    device = "cuda" if torch.cuda.is_available() else "cpu"
    use_4bit = device == "cuda"
    max_examples = 50 if demo_mode else None

    print(f"\n{'='*60}")
    print(f"  QLoRA Fine-Tuning")
    print(f"{'='*60}")
    print(f"  Model    : {model_id}")
    print(f"  Device   : {device.upper()}")
    print(f"  4-bit    : {use_4bit}")
    print(f"  Epochs   : {epochs}")
    print(f"  Demo mode: {demo_mode} (max {max_examples} examples)")
    print(f"  Output   : {output_dir}")
    print(f"{'='*60}\n")

    # ── Load training data ─────────────────────────────────────────────────────
    print("Loading training data…")
    train_raw = load_jsonl(TRAIN_DATA, max_examples)
    val_raw = load_jsonl(VAL_DATA, max_examples // 5 if max_examples else None)

    # ── Load tokenizer ─────────────────────────────────────────────────────────
    print(f"Loading tokenizer: {model_id}…")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # ── Format dataset ─────────────────────────────────────────────────────────
    print("Formatting dataset with chat template…")
    train_texts = [format_for_training(ex, tokenizer) for ex in train_raw]
    val_texts   = [format_for_training(ex, tokenizer) for ex in val_raw]

    train_dataset = Dataset.from_dict({"text": train_texts})
    val_dataset   = Dataset.from_dict({"text": val_texts})

    print(f"  Training examples  : {len(train_dataset)}")
    print(f"  Validation examples: {len(val_dataset)}")

    # ── Load model ─────────────────────────────────────────────────────────────
    print(f"\nLoading model: {model_id}…")
    quant_config = None
    if use_4bit:
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=quant_config,
        device_map="auto" if device == "cuda" else None,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        trust_remote_code=True,
    )
    model.config.use_cache = False

    # ── LoRA configuration ─────────────────────────────────────────────────────
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=lora_rank,
        lora_alpha=lora_rank * 2,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
    )

    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"  Trainable params: {trainable:,} / {total:,} ({100*trainable/total:.3f}%)")

    # ── Training arguments ─────────────────────────────────────────────────────
    training_args = SFTConfig(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=4,
        learning_rate=learning_rate,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        fp16=use_4bit,
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        report_to="none",
        max_seq_length=max_seq_length,
        dataset_text_field="text",
        peft_config=lora_config,
    )

    # ── Train ─────────────────────────────────────────────────────────────────
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,
    )

    print(f"\nStarting training…")
    result = trainer.train()

    print(f"\nTraining complete!")
    print(f"  Final train loss : {result.training_loss:.4f}")
    print(f"  Total steps      : {result.global_step}")
    print(f"  Training time    : {result.metrics.get('train_runtime', 0):.0f}s")

    # ── Save adapter ───────────────────────────────────────────────────────────
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    trainer.model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

    print(f"\n✔ LoRA adapter saved to: {output_dir}")
    print(f"  To use: load base model + adapter with PEFT, or merge weights.")
    print(f"  Merge command: see training/merge_adapter.py")

    # Save training summary
    summary = {
        "base_model": model_id,
        "epochs": epochs,
        "train_examples": len(train_dataset),
        "val_examples": len(val_dataset),
        "final_train_loss": result.training_loss,
        "lora_rank": lora_rank,
        "device": device,
        "demo_mode": demo_mode,
    }
    with open(Path(output_dir) / "training_summary.json", "w") as f:
        json.dump(summary, f, indent=2)


# ══════════════════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="QLoRA fine-tuning on retail + MIMIC data.")
    parser.add_argument(
        "--model",
        default="microsoft/Phi-3.5-mini-instruct",
        help="HuggingFace model ID to fine-tune.",
    )
    parser.add_argument("--epochs", type=int, default=3, help="Training epochs.")
    parser.add_argument("--batch-size", type=int, default=1, help="Per-device batch size.")
    parser.add_argument("--lora-rank", type=int, default=16, help="LoRA rank (r).")
    parser.add_argument("--lr", type=float, default=2e-4, help="Learning rate.")
    parser.add_argument("--max-seq-len", type=int, default=1024, help="Max sequence length.")
    parser.add_argument("--output-dir", default=str(ADAPTER_DIR), help="Adapter output dir.")
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Demo mode: 50 examples, 1 epoch. Works without GPU.",
    )
    args = parser.parse_args()

    train(
        model_id=args.model,
        epochs=1 if args.demo else args.epochs,
        batch_size=args.batch_size,
        max_seq_length=args.max_seq_len,
        lora_rank=args.lora_rank,
        learning_rate=args.lr,
        demo_mode=args.demo,
        output_dir=args.output_dir,
    )
